apiVersion: v1
kind: Service
metadata:
  name: kube-assingnment1-service
spec:
  selector:
    app: kube-assingnment1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30050
  type: NodePort
