apiVersion: v1
kind: Service
metadata:
  name: kube-assingnment-service
spec:
  selector:
    app: kube-assingnment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30040
  type: NodePort
